sudo: required

services:
  - docker

language: node_js
node_js:
  - 12

dist: bionic

cache:
  npm

branches:
  only:
    - master

env:
  global:
    - DOCKER_IMAGE=mag20/node-graphql
    - DOCKER_TAG=$TRAVIS_JOB_NUMBER

jobs:
  include:
    - stage: build
      before_install:
        - npm i -g npm@6.14.4
      script:
        - npm run build
    - stage: docker build
      script:
        - docker build -t "$DOCKER_IMAGE":latest .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag "$DOCKER_IMAGE":latest "$DOCKER_IMAGE":"$DOCKER_TAG"
        - docker push "$DOCKER_IMAGE":latest
        - docker push "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":latest